"""rename department

Revision ID: 9c9b31821f2c
Revises: 31fa0f1fe89f
Create Date: 2024-06-25 10:14:21.069936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9b31821f2c'
down_revision = '31fa0f1fe89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
